# Generated by Django 3.2 on 2021-05-01 09:48

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IndianStates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fid', models.IntegerField()),
                ('id_0', models.IntegerField()),
                ('iso', models.CharField(max_length=3)),
                ('name_0', models.CharField(max_length=5)),
                ('id_1', models.IntegerField()),
                ('name_1', models.CharField(max_length=22)),
                ('nl_name_1', models.CharField(max_length=1, null=True)),
                ('varname_1', models.CharField(max_length=100, null=True)),
                ('type_1', models.CharField(max_length=14)),
                ('engtype_1', models.CharField(max_length=15)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
            options={
                'verbose_name_plural': 'Indian States',
            },
        ),
    ]
